#!/bin/python3

import math
import os
import random
import re
import sys

def getRoundResult(winning_suit, suit1, number1, suit2, number2):
    if suit1 == winning_suit and suit2!=winning_suit:
        return 'Player 1 wins'
    elif suit2 == winning_suit and suit1!=winning_suit:
        return 'Player 2 wins'
    else:
        if(number1>number2):
            return 'Player 1 wins'
        elif(number2>number1):
            return 'Player 2 wins'
        else:
            return 'Draw'

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    winning_suit = input()[0]

    n = int(input().strip())

    for n_itr in range(n):
        first_multiple_input = input().rstrip().split()

        suit1 = first_multiple_input[0][0]

        number1 = int(first_multiple_input[1])

        suit2 = first_multiple_input[2][0]

        number2 = int(first_multiple_input[3])

        result = getRoundResult(winning_suit, suit1, number1, suit2, number2)

        fptr.write(result + '\n')

    fptr.close()
