#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hackerlandRadioTransmitters function below.
def hackerlandRadioTransmitters(x, k):
    length = len(x)
    x.sort()
    i=j=counter=0
    while i<length:
        temp = x[i]+k
        while i<length and temp>=x[i]:
            i+=1
        i-=1
        j=i
        counter+=1
        while i<length and x[i]<=x[j]+k:
            i+=1
    return counter

nk = input().split()

n = int(nk[0])

k = int(nk[1])

x = list(map(int, input().rstrip().split()))

result = hackerlandRadioTransmitters(x, k)
print(result)

  
