#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the larrysArray function below.
def larrysArray(arr):
    n = len(arr)
    inv_count = 0
    for i in range(n): 
        for j in range(i + 1, n): 
            if (arr[i] > arr[j]): 
                inv_count += 1
    
        
    if inv_count%2==0:
        return "YES"
    else:
        return "NO"


t = int(input())

for t_itr in range(t):
    n = int(input())

    A = list(map(int, input().rstrip().split()))

    result = larrysArray(A)
    
    print(result)
