#!/bin/python3

import math
import os
import random
import re
import sys
global a
a={0:1,1:1,2:2,3:4}
def stepPerms(n):
    global a
    if n in a:
        return a[n]
    else:
        result=stepPerms(n-1)+stepPerms(n-2)+stepPerms(n-3)
        if n not in a:
            a[n]=result
        return result%10000000007

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = int(input())

    for s_itr in range(s):
        n = int(input())

        res = stepPerms(n)

        fptr.write(str(res) + '\n')

    fptr.close()
