#!/bin/python3

def gridSearch(G, P):
    flag=0
    a = len(P)
    b = len(P[0])
    for i in range(len(G)-a+1):
        for j in range(len(G[i])-b+1):
            if G[i][j]==P[0][0]:
                flag=1
                for k in range(a):
                    if G[i+k][j:j+b]!=P[k]:
                        flag=0
            if flag==1:
                return "YES"
            
    return "NO"


t = int(input())

for t_itr in range(t):
    RC = input().split()

    R = int(RC[0])

    C = int(RC[1])

    G = []

    for _ in range(R):
        G_item = input()
        G.append(G_item)

    rc = input().split()

    r = int(rc[0])

    c = int(rc[1])

    P = []

    for _ in range(r):
        P_item = input()
        P.append(P_item)

    result = gridSearch(G, P)

    print(result)
